/**********************************************************************
 Name:  accountTriggerAction
 Other classes used:
 Tested in class:  AccountTriggerAction_Tests.cls
======================================================
Purpose:
    Single trigger for Account.
    We are using a trigger framework. Business logic implemented in Account Trigger handler.
    This class is used to build the logic
======================================================
History
-------
VERSION         AUTHOR                  DATE            DETAIL
 1.0         Saritha anumandla       11/4/2019        ORIGINAL DEVELOPMENT

***********************************************************************/


public with sharing class accountTriggerAction {
    //Logic to be implemented on the Account objects



}