/**********************************************************************
 Name:  accountTriggerHandler_Test
 Other classes used:
 Tested in class:  AccountTriggerHandlerTests.cls
======================================================
Purpose:
    Single trigger for Account.
    We are using a trigger framework. Business logic implemented in Account Trigger handler.
======================================================
History
-------
VERSION         AUTHOR                  DATE            DETAIL
 1.0         Saritha anumandla       11/4/2019        ORIGINAL DEVELOPMENT

***********************************************************************//**

 */

public with sharing class accountTriggerHandler_Test {

}