/**********************************************************************
 Name:  TestFactory.cls
======================================================
Purpose:

	Utility class used in test methods for data creation.  Prevents duplication of code in testmethods to set up test data.
	Please DO NOT make any changes to the existing functions of the class as it will cause failures of many unit tests.
	If you think there needs to be a change, co-ordinate with CSI team first.
======================================================
History
-------
VERSION		AUTHOR				DATE			DETAIL
1.0	    saritha anumandla	11/04/2019		INITIAL DEVELOPMENT

***********************************************************************/

public with sharing class Testfactory {
    //getadmin use
    //get apiuser
    //create admin user
    //create account
    //create contact
    //create opportunity
    //create campaign
    //create product
    //create quote
    //create a case


}